// resample(): Sprague (1880) quintic interpolation per CIE 167:2005.
// Three independent checks: algebraic (exact at nodes, reproduces quintic
// polynomials), oracle (colour-science's SpragueInterpolator, fixture
// generated by tools/build-sprague-oracle.py), and derivational (Planck's
// law evaluated at 5 nm then resampled to 1 nm must match Planck's law
// evaluated at 1 nm — the analytic curve is the ground truth).

import test from 'node:test';
import assert from 'node:assert';
import { readFileSync } from 'node:fs';
import { resample, planckianSPD, spectrumXy } from '../src/spectral/index.js';
import { CMF_1931_2_1NM } from '../src/spectral/data-1nm.js';

const oracle = JSON.parse(readFileSync(new URL('./fixtures/sprague-oracle.json', import.meta.url)));

test('source nodes are reproduced exactly', () => {
  const spd = { start: 380, step: 5, values: [1.18, 1.48, 1.84, 2.15, 3.44, 15.69, 3.85, 3.74] };
  const out = resample(spd, { step: 5 });
  assert.deepStrictEqual(out.values, spd.values);
  const fine = resample(spd, { step: 1 });
  for (let i = 0; i < spd.values.length; i++) {
    assert.strictEqual(fine.values[i * 5], spd.values[i], `node ${i}`);
  }
});

test('interior segments reproduce quartics to rounding', () => {
  // The osculating construction matches endpoint values plus 5-point
  // central-difference derivatives, which are exact through degree 4 —
  // so quartics reproduce exactly away from the boundary segments.
  // (Quintics do NOT reproduce: the first-derivative stencil has an
  // h⁴f⁽⁵⁾ error term. The boundary polynomials are approximations tuned
  // for spectra, not growing polynomials — tested on Planck below.)
  const q4 = (x) => (((2 * x - 5) * x + 3) * x - 7) * x + 11;
  const xs = Array.from({ length: 9 }, (_, i) => i * 2); // 0..16 step 2
  const spd = { start: 0, step: 2, values: xs.map(q4) };
  const out = resample(spd, { step: 0.5 });
  out.values.forEach((v, k) => {
    const x = 0.5 * k;
    if (x < 4 || x > 12) return; // interior only
    const scale = Math.max(1, Math.abs(q4(x)));
    assert.ok(Math.abs(v - q4(x)) / scale < 1e-13, `x=${x}: ${v} vs ${q4(x)}`);
  });
});

test('matches the colour-science SpragueInterpolator oracle', () => {
  for (const c of oracle.cases) {
    const out = resample(c.input, c.target);
    assert.strictEqual(out.values.length, c.expected.length, c.name);
    c.expected.forEach((e, k) => {
      assert.ok(Math.abs(out.values[k] - e) < 1e-6, `${c.name} [${k}]: ${out.values[k]} vs ${e}`);
    });
  }
});

test('Planck 5 nm resampled to 1 nm tracks Planck 1 nm', () => {
  const coarse = planckianSPD(2856, { start: 380, step: 5, end: 780 });
  const fine = planckianSPD(2856, { start: 380, step: 1, end: 780 });
  const out = resample(coarse, { step: 1 });
  let interior = 0, boundary = 0;
  out.values.forEach((v, k) => {
    const nm = 380 + k;
    const rel = Math.abs(v - fine.values[k]) / fine.values[k];
    if (nm >= 390 && nm <= 770) interior = Math.max(interior, rel);
    else boundary = Math.max(boundary, rel);
  });
  assert.ok(interior < 1e-8, `interior max relative error ${interior}`);
  assert.ok(boundary < 1e-3, `boundary max relative error ${boundary}`);
  // And the chromaticity is indistinguishable.
  const a = spectrumXy(out, { cmf: CMF_1931_2_1NM });
  const b = spectrumXy(fine, { cmf: CMF_1931_2_1NM });
  assert.ok(Math.abs(a[0] - b[0]) < 1e-7 && Math.abs(a[1] - b[1]) < 1e-7, `${a} vs ${b}`);
});

test('refuses to extrapolate and to run on short tables', () => {
  const spd = { start: 400, step: 10, values: [1, 2, 3, 4, 5, 6] };
  assert.throws(() => resample(spd, { start: 390 }), RangeError);
  assert.throws(() => resample(spd, { end: 460 }), RangeError);
  assert.doesNotThrow(() => resample(spd, { start: 400, end: 450, step: 1 }));
  assert.throws(() => resample({ start: 0, step: 1, values: [1, 2, 3, 4, 5] }), RangeError);
});
