// Hosek–Wilkie sky dome. Three layers of verification:
//  1. Exact-index structural tests — at the Bézier endpoints and integer
//     turbidity/binary albedo, the cooked configuration must EQUAL specific
//     raw dataset entries; this pins the port's indexing bit-for-bit.
//  2. Blend linearity — the albedo/turbidity interpolation is linear by
//     construction, so cooked states must satisfy exact mixture identities.
//  3. Physics — zenith bluer than horizon, positive radiance, plausible CCT.
// Plus, when test/fixtures/hosek-oracle.json exists (generated by
// tools/build-sky-oracle.js, which compiles the authors' reference C),
// digit-level comparison against the reference implementation itself.

import test from 'node:test';
import assert from 'node:assert';
import { existsSync, readFileSync } from 'node:fs';
import { skyModel, skyRadiance, skySPD, SKY_WL } from '../src/sky/index.js';
import { SKY_DATASETS, SKY_RADIANCES } from '../src/sky/data.js';
import { spectrumXy, cctOf } from '../src/spectral/index.js';

const PI = Math.PI;

test('domain validation', () => {
  assert.throws(() => skyModel({ elevation: -0.1 }), RangeError);
  assert.throws(() => skyModel({ elevation: 2 }), RangeError);
  assert.throws(() => skyModel({ elevation: 0.5, turbidity: 0.5 }), RangeError);
  assert.throws(() => skyModel({ elevation: 0.5, turbidity: 11 }), RangeError);
  assert.throws(() => skyModel({ elevation: 0.5, albedo: 1.5 }), RangeError);
});

test('Bézier endpoints read exact dataset entries (indexing pinned)', () => {
  // elevation π/2 → t = 1 → control point 5; turbidity 4 (integer, rem 0),
  // albedo 0 → only the alb-0 low-turbidity corner contributes.
  const hi = skyModel({ elevation: PI / 2, turbidity: 4, albedo: 0 });
  for (let wl = 0; wl < SKY_WL.length; wl++) {
    for (let i = 0; i < 9; i++) {
      assert.strictEqual(hi.configs[wl][i], SKY_DATASETS[wl][9 * 6 * 3 + i + 45], `cp5 wl${wl} c${i}`);
    }
    assert.strictEqual(hi.radiances[wl], SKY_RADIANCES[wl][6 * 3 + 5], `rad cp5 wl${wl}`);
  }

  // elevation 0 → t = 0 → control point 0
  const lo = skyModel({ elevation: 0, turbidity: 4, albedo: 0 });
  for (let wl = 0; wl < SKY_WL.length; wl++) {
    for (let i = 0; i < 9; i++) {
      assert.strictEqual(lo.configs[wl][i], SKY_DATASETS[wl][9 * 6 * 3 + i], `cp0 wl${wl} c${i}`);
    }
    assert.strictEqual(lo.radiances[wl], SKY_RADIANCES[wl][6 * 3], `rad cp0 wl${wl}`);
  }

  // albedo 1 reads the second half of the dataset
  const alb1 = skyModel({ elevation: PI / 2, turbidity: 4, albedo: 1 });
  for (let i = 0; i < 9; i++) {
    assert.strictEqual(alb1.configs[0][i], SKY_DATASETS[0][9 * 6 * 10 + 9 * 6 * 3 + i + 45], `alb1 c${i}`);
  }

  // turbidity 10 must not read past the table (the reference's early return)
  const t10 = skyModel({ elevation: 0.7, turbidity: 10, albedo: 0.5 });
  assert.ok(t10.configs.every((c) => c.every(Number.isFinite)));
});

test('the albedo and turbidity blends are exactly linear', () => {
  const opts = { elevation: 0.6 };
  const a0 = skyModel({ ...opts, turbidity: 4, albedo: 0 });
  const a1 = skyModel({ ...opts, turbidity: 4, albedo: 1 });
  const aq = skyModel({ ...opts, turbidity: 4, albedo: 0.25 });
  const t4 = skyModel({ ...opts, turbidity: 4, albedo: 0.3 });
  const t5 = skyModel({ ...opts, turbidity: 5, albedo: 0.3 });
  const th = skyModel({ ...opts, turbidity: 4.5, albedo: 0.3 });
  for (let wl = 0; wl < SKY_WL.length; wl++) {
    for (let i = 0; i < 9; i++) {
      const albMix = 0.75 * a0.configs[wl][i] + 0.25 * a1.configs[wl][i];
      assert.ok(Math.abs(aq.configs[wl][i] - albMix) < 1e-12 * (1 + Math.abs(albMix)), `albedo blend wl${wl} c${i}`);
      const turbMix = 0.5 * t4.configs[wl][i] + 0.5 * t5.configs[wl][i];
      assert.ok(Math.abs(th.configs[wl][i] - turbMix) < 1e-12 * (1 + Math.abs(turbMix)), `turbidity blend wl${wl} c${i}`);
    }
  }
});

test('physics: zenith is bluer and colder than the horizon', () => {
  const state = skyModel({ elevation: 30 * (PI / 180), turbidity: 3, albedo: 0.1 });
  const sunTheta = PI / 2 - state.elevation;

  // radiance positive across the dome and spectrum
  for (const theta of [0, 0.5, 1.0, 1.45]) {
    for (const gamma of [0.2, 1.0, 2.5]) {
      for (const wl of [360, 440, 560, 680]) {
        const r = skyRadiance(state, theta, gamma, wl);
        assert.ok(r > 0, `radiance(θ${theta}, γ${gamma}, ${wl}nm) = ${r}`);
      }
    }
  }

  // zenith vs a view 5° above the horizon, both away from the sun
  const zenith = spectrumXy(skySPD(state, 0, sunTheta));
  const horizon = spectrumXy(skySPD(state, 85 * (PI / 180), PI / 2));
  assert.ok(zenith[0] < horizon[0], `x zenith ${zenith[0]} vs horizon ${horizon[0]}`);

  const zenithCct = cctOf(zenith).cct;
  const horizonCct = cctOf(horizon).cct;
  assert.ok(zenithCct > horizonCct, `CCT zenith ${zenithCct} vs horizon ${horizonCct}`);
  assert.ok(zenithCct > 6500, `clear-sky zenith CCT ${zenithCct} (expect well above daylight)`);
});

test('higher turbidity desaturates the zenith sky', () => {
  const sunTheta = PI / 2 - 0.6;
  const clear = spectrumXy(skySPD(skyModel({ elevation: 0.6, turbidity: 1.5 }), 0, sunTheta));
  const hazy = spectrumXy(skySPD(skyModel({ elevation: 0.6, turbidity: 8 }), 0, sunTheta));
  // hazier → closer to white → larger x (warmer, less blue)
  assert.ok(hazy[0] > clear[0], `x hazy ${hazy[0]} vs clear ${clear[0]}`);
});

test('out-of-band wavelengths return 0, with the reference fade above 720', () => {
  const state = skyModel({ elevation: 0.8 });
  assert.strictEqual(skyRadiance(state, 0.3, 0.9, 280), 0);
  assert.strictEqual(skyRadiance(state, 0.3, 0.9, 761), 0);
  const at720 = skyRadiance(state, 0.3, 0.9, 720);
  const at740 = skyRadiance(state, 0.3, 0.9, 740);
  assert.ok(at740 > 0 && at740 < at720, `linear fade: 720→${at720}, 740→${at740}`);
});

const fixture = new URL('./fixtures/hosek-oracle.json', import.meta.url);
test('digit-level agreement with the compiled reference implementation',
  { skip: !existsSync(fixture) && 'run tools/build-sky-oracle.js (needs cc) to generate the fixture' },
  () => {
    const { elevations, turbidities, albedos, views, wavelengths, rows } =
      JSON.parse(readFileSync(fixture, 'utf8'));
    let worst = 0;
    const states = new Map();
    for (const [e, t, a, v, w, expected] of rows) {
      const key = `${e}|${t}|${a}`;
      if (!states.has(key)) {
        states.set(key, skyModel({ elevation: elevations[e], turbidity: turbidities[t], albedo: albedos[a] }));
      }
      const got = skyRadiance(states.get(key), views[v][0], views[v][1], wavelengths[w]);
      worst = Math.max(worst, Math.abs(got - expected) / (1 + Math.abs(expected)));
    }
    assert.ok(worst < 1e-12, `worst relative disagreement ${worst.toExponential(2)}`);
  });
